### ISSUE TITLE
'tab' duplicate strings

### ISSUE THREAD

**Issue by Dimozavr** [yousifj129/VimiCode#11]
'tab' symbol can duplicate your string because of completer abilities
1) write the word, that tab can fully complete
2) set cursor somewhere in the middle of this word
3) press any symbol
4) press backspace
5) press tab
![image](https://github.com/user-attachments/assets/8aa1cf57-1966-4125-9a93-06430f78397a)

**Comment by yousifj129** [comment]
Solved the problem
