### ISSUE TITLE
syntax highlighter doesn't work correctly

### ISSUE THREAD

**Issue by yousifj129** [yousifj129/VimiCode#3]
the  highlighter doesn't recolor all the text in the same time, you have to go block by block to make it update colors for function names

**Comment by amritupreti** [comment]
Can you clarify more? I run the code and it is highlighting all files irrespective of the file extension.
Do you want me to fix highlighting for only .py file?

I think issue is your CodeEditor does not know the file extension. It is only getting file content.

**Comment by yousifj129** [comment]
> Can you clarify more? I run the code and it is highlighting all files irrespective of the file extension.
> Do you want me to fix highlighting for only .py file?
> 
> I think issue is your CodeEditor does not know the file extension. It is only getting file content.

Oh, I solved and forgot to close the issue
